#!/bin/zsh

SCRIPT_DIR="${0:A:h}"
"${SCRIPT_DIR}/rerunnables"

waybar &
swaybg -i ~/Documents/misc/wallpapers/current &

mako --default-timeout=5000 &

mkfifo /tmp/wobpipe &
tail -f /tmp/wobpipe | wob &

nm-applet &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=niri
